apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-app-config
  namespace: devops
data:
  APPLICATION_NAME: "devops-spring-app"
  SPRING_PROFILES_ACTIVE: "prod"
  SERVER_PORT: "8080"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  SPRING_JPA_SHOW_SQL: "false"
