apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app-deployment
  namespace: devops
  labels:
    app: spring-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      containers:
        - name: spring-app
          image: shiliyasmine/jenkins-springboot:latest
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: APPLICATION_NAME
              valueFrom:
                configMapKeyRef:
                  name: spring-app-config
                  key: APPLICATION_NAME
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: spring-app-config
                  key: SPRING_PROFILES_ACTIVE
            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: spring-app-config
                  key: SERVER_PORT
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              valueFrom:
                configMapKeyRef:
                  name: spring-app-config
                  key: SPRING_JPA_HIBERNATE_DDL_AUTO
            - name: SPRING_JPA_SHOW_SQL
              valueFrom:
                configMapKeyRef:
                  name: spring-app-config
                  key: SPRING_JPA_SHOW_SQL
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: spring-app-secret
                  key: database-url
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: spring-app-secret
                  key: database-username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: spring-app-secret
                  key: database-password
