apiVersion: v1
kind: Secret
metadata:
  name: spring-app-secret
  namespace: devops
type: Opaque
data:
  database-url: amRiYzpteXNxbDovL215c3FsLXNlcnZpY2UuZGV2b3BzLnN2Yy5jbHVzdGVyLmxvY2FsOjMzMDYvc3ByaW5nZGI=
  database-username: cm9vdA==
  database-password: cGFzc3dvcmQxMjM=
